trigger:
- production

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    cd lotriet-logistics
    npm install primeicons primeng tailwindcss postcss autoprefixer
    npm install
    ng build --output-path=dist/lotriet-logistics/browser
  displayName: 'Install Angular CLI, Install Packages, and Build Project'

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'lotriet-logistics' # Location of your application code
    output_location: 'dist/lotriet-logistics/browser' # Location of the build output relative to app_location
    azure_static_web_apps_api_token: $(deployment_token) # Set this as a secret variable in your pipeline
  displayName: 'Deploy to Azure Static Web Apps'
